on:
    - pull_request
    - push

name: build

jobs:
    codeception:
        name: PHP ${{ matrix.php-version }}-mysql-${{ matrix.mysql-version }}
        env:
            extensions: pdo, pdo_mysql, gd, mbstring
            key: cache-v1
            TEST_MYSQL_HOST: 127.0.0.1
            TEST_MYSQL_DB: yiitest
            TEST_MYSQL_USER: root
            TEST_MYSQL_PASS: root

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os:
                    - ubuntu-latest

                php-version:
                    - "7.4"
                    - "8.0"
                    - "8.1"

                mysql-version:
                    - "latest"

        services:
            mysql:
                image: mysql:${{ matrix.mysql-version }}
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: yiitest
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup cache environment
              id: cache-env
              uses: shivammathur/cache-extensions@v1
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: ${{ env.extensions }}
                  key: ${{ env.key }}

            - name: Cache extensions
              uses: actions/cache@v1
              with:
                  path: ${{ steps.cache-env.outputs.dir }}
                  key: ${{ steps.cache-env.outputs.key }}
                  restore-keys: ${{ steps.cache-env.outputs.key }}

            - name: Install PHP with extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: ${{ env.extensions }}
                  ini-values: date.timezone='UTC'

            - name: Determine composer cache directory
              if: matrix.os == 'ubuntu-latest'
              run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

            - name: Cache dependencies installed with composer
              uses: actions/cache@v1
              with:
                  path: ${{ env.COMPOSER_CACHE_DIR }}
                  key: php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('**/composer.json') }}
                  restore-keys: |
                      php${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-

            - name: Install dependencies with composer
              run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            - name: Run migrations
              run: vendor/bin/yii migrate/up --appconfig="tests/_data/console.php" --interactive=0 --color=1

            - name: Build needed classes with codeception
              run: vendor/bin/codecept build --ansi

            - name: Run tests with codeception
              run: vendor/bin/codecept run --ansi
